from fpdf import FPDF
import pandas as pd
from getDataFrame import getData
from utilityFunction import cut_msg, getFileName
from getCode import getHomePage
from fpdf import FPDF, HTMLMixin
import os

title = "Wats2PDF"
# LINKS
fb_link = "#"
t_link = "https://twitter.com/nishantssoni"
github_link = "https://github.com/nishantssoni"
kaggle = "https://www.kaggle.com/nishantssoni"
website = "#"
linkedin = "#"

class PDF(FPDF, HTMLMixin):
    def header(self):
        # font
        self.set_font('helvetica','B',9)

        # Calculate width of title and position
        title_width = self.get_string_width(title) + 6
        document_width = self.w
        self.set_x( (document_width - title_width) / 2 )

                # colors of frams backgroud and text
        self.set_draw_color(0, 250, 0) # border = blue
        self.set_fill_color(0, 204, 102) # background = yellow
        self.set_text_color(220, 220, 220) # text = red

        # thickness of frame or border
        self.set_line_width(.1)
        # title
        self.cell(title_width, 5, title, border=1, ln=1, align='C', fill=1)

        # line break
        self.ln(10)

    def footer(self):
        # set position of the footer
        self.set_y(-15)

        # set font
        self.set_font('helvetica', 'I', 8)


        # page number
        # self.cell(0, 5, f'{self.page_no()} / {{nb}}', align='R',ln=1)

        # links
        self.set_text_color(50,50,200)
        self.set_font('helvetica','U',7)
        self.cell(20, 5, f'facebook',link=fb_link, align='C')
        self.cell(20, 5, f'github',link=github_link, align='C')
        self.cell(20, 5, f'twitter',link=t_link, align='C')
        self.cell(20, 5, f'website',link=website, align='C')
        self.cell(20, 5, f'kaggle',link=kaggle, align='C')
        self.cell(20, 5, f'linkedin',link=linkedin, align='C')

        
        # note
        self.set_font('Times','I',6)
        self.set_text_color(220, 0,0)
        self.cell(40, 5, f'This PDF is generated by Wats2PDF.',link=linkedin)
        
        # page number
        self.set_text_color(50,50,50)
        self.set_font('helvetica','',8)
        self.cell(0, 5, f'{self.page_no()} / {{nb}}',align='R')
        


# getting chats data
chat_file_name = getFileName()
if chat_file_name == "end":
    exit()

chats, persons = getData(chat_file_name)

# pdf object
pdf = PDF(orientation='P', unit='mm', format='A4')

# 
pdf.add_page()
pdf.set_font('helvetica','',30)
pdf.write_html(getHomePage(persons[0], persons[1]))



# add page
pdf.add_page()






pdf.set_font('helvetica','',9)

aut = ''
WOC = 90
HOC = 5
t = [0,0,0]
for i,j,hr,mi,mo,ye,da,me in chats[['author','message','hour','minute','month','year','day','meridiem']].values:
    
    
    if (t[0] != da) or (t[1] != mo) or (t[2] != ye):
        pdf.set_fill_color(204, 204, 255)
        pdf.set_line_width(1)
        pdf.set_font('Times','B',9)
        pdf.ln(5)
        pdf.cell(0,HOC,f"{da}-{mo}-{ye}",ln=1,border=0,align='C',fill=1)
        t[0] = da
        t[1] = mo
        t[2] = ye
        pdf.ln(5)
     
    space = 10 if i == persons[0] else 110
    if(aut == '' or aut != i):
        pdf.ln(6)
        aut = i
        pdf.set_x(space + (WOC//4))
        pdf.set_fill_color(200, 220, 130)
        pdf.set_line_width(1)
        pdf.set_font('helvetica','I',7)
        pdf.cell(WOC//2,HOC,f"{i}",ln=1,border=0,align='C',fill=1)
        pdf.ln(2)

    
    for msg in cut_msg(j, 55):
        pdf.set_x(space)
        pdf.set_font('helvetica','',8)
        if aut == persons[0]:
            pdf.set_fill_color(220, 248, 198)
        else:
            pdf.set_fill_color(190, 190, 190)
        pdf.set_line_width(1)
        pdf.cell(WOC,HOC,f"{msg}",ln=1,border=0,align='C',fill=1)
    
    # DATE AND TIME
    pdf.set_x(space)
    pdf.set_font('Times','',6)
    pdf.cell(WOC,HOC-1,f"{hr}:{mi} {me}",ln=1,border=0,align='R')  
    

pdf_name = chat_file_name[:-4] + ".pdf"
pdf.output(name=pdf_name)
print("your pdf is created, and placed in your_exported_txt")